version: '3'

networks:
  gateway:
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    expose:
      - "15672"
      - "5672"
      - "25676"
    networks: 
      - gateway
    ports:
      - "8086:15672"
