version: '3'

networks: 
  gateway:
    external: true
  cluster-ms:
    driver: bridge

services:
  # API
  app:
    container_name: "ms-order-api"
    environment:
      NODE_ENV: development
      DB_DATABASE: ms
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: "ms-order-database"
      DB_PORT: "5432"
      PORT: "8080"
    expose:
      - "8080"
    build: 
      context: .
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    networks:
      - gateway
      - cluster-ms
    depends_on:
      - db
    volumes:
      - ./:/home/node/app
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; npm run startup:dev"

  # BD
  db:
    image: postgres:11.2
    container_name: "ms-order-database"
    networks: 
      - cluster-ms
    environment:
      POSTGRES_DB: ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres